[package]
name = "clay-layout"
version = "0.2.0"
edition = "2021"
description = "Rust bindings for Clay, a UI layout library written in C."
keywords = ["clay", "ui", "layout", "bindings", "no_std"]
repository = "https://github.com/clay-ui-rs/clay"
readme = "README.md"
license-file = "LICENSE.md"
exclude = ["scripts/*", ".vscode/*", ".github/*", ".cargo/*"]

[build-dependencies]
cc = "1.0"

[features]
default = ["std"]
raylib-renderer = ["raylib"]
skia-renderer = ["skia-safe"]

std = []
wasm = []
debug = []

[dependencies]
skia-safe = { version = "0.82.0", features = ["gl"], optional = true }
raylib = { version = "5.0.2", optional = true }

[dev-dependencies]
winit = "0.30.9"
wgpu = "24.0.1"
pollster = "0.2"
bytemuck = { version = "1.16", features = [ "derive" ] }
glyphon = "0.8.0"

[[example]]
name = "raylib_renderer"
path = "examples/raylib_renderer.rs"
required-features = ["raylib", "std"]
